python tools/test.py configs/oafd/hyp_test/01_o4_r6_w0.8.py work_dirs/hyp_test/01/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/02_o4_r5_w0.8.py work_dirs/hyp_test/02/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/03_o4_r4_w0.8.py work_dirs/hyp_test/03/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/04_o4_r3_w0.8.py work_dirs/hyp_test/04/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/05_o4_r2_w0.8.py work_dirs/hyp_test/05/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/06_o8_r6_w1.6.py work_dirs/hyp_test/06/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/07_o8_r5_w1.6.py work_dirs/hyp_test/07/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/08_o8_r4_w1.6.py work_dirs/hyp_test/08/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/09_o8_r3_w1.6.py work_dirs/hyp_test/09/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/10_o8_r2_w1.6.py work_dirs/hyp_test/10/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/11_o2_r6_w0.4.py work_dirs/hyp_test/11/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/12_o2_r5_w0.4.py work_dirs/hyp_test/12/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/13_o2_r4_w0.4.py work_dirs/hyp_test/13/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/14_o2_r3_w0.4.py work_dirs/hyp_test/14/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/15_o2_r2_w0.4.py work_dirs/hyp_test/15/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/16_o1_r6_w0.2.py work_dirs/hyp_test/16/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/17_o1_r5_w0.2.py work_dirs/hyp_test/17/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/18_o1_r4_w0.2.py work_dirs/hyp_test/18/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/19_o1_r3_w0.2.py work_dirs/hyp_test/19/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/20_o1_r2_w0.2.py work_dirs/hyp_test/20/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/21_o8_r1_w1.6.py work_dirs/hyp_test/21/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/22_o4_r1_w0.8.py work_dirs/hyp_test/22/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/23_o2_r1_w0.4.py work_dirs/hyp_test/23/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/24_o1_r1_w0.2.py work_dirs/hyp_test/24/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/25_o8_r0_w1.6.py work_dirs/hyp_test/25/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/26_o4_r0_w0.8.py work_dirs/hyp_test/26/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/27_o2_r0_w0.4.py work_dirs/hyp_test/27/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/28_o1_r0_w0.4.py work_dirs/hyp_test/28/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/29_o1_r1_w0.1.py work_dirs/hyp_test/29/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/30_o1_r1_w0.3.py work_dirs/hyp_test/30/latest.pth --eval=mAP --eval-options iou_thr=0.75
python tools/test.py configs/oafd/hyp_test/31_o1_r1_w0.4.py work_dirs/hyp_test/31/latest.pth --eval=mAP --eval-options iou_thr=0.75
